---
# install and configure ufw
- apt:
    name: ufw
- ufw:
   rule: allow
   name: ssh
- ufw:
   rule: allow
   port: 1194
   proto: udp
- replace:
   dest: /etc/default/ufw
   regexp: 'DEFAULT_FORWARD_POLICY="DROP"'
   replace: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
- replace:
   dest: /etc/ufw/before.rules
   regexp: 'DEFAULT_FORWARD_POLICY="DROP"'
   replace: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
- blockinfile:
   dest: /etc/ufw/before.rules
   block: |
     # START OPENVPN RULES
     # NAT table rules
     *nat
     :POSTROUTING ACCEPT [0:0]
     # Allow traffic from OpenVPN client to eth0
     -A POSTROUTING -s 10.8.0.0/8 -o eth0 -j MASQUERADE
     COMMIT
     # END OPENVPN RULES
- ufw:
   state: enabled
   policy: allow
...
