---
# Configure and Build the Certificate Authority
- name: copy over the Easy-RSA generation scripts.
  shell: cp -r /usr/share/easy-rsa/ /etc/openvpn # copy module does not support recursive

- name: create a directory to house the key
  file:
   path: /etc/openvpn/easy-rsa/keys
   state: directory

- name: set parameters for our certificate
  replace:
   dest: /etc/openvpn/easy-rsa/vars
   regexp: 'export KEY_NAME="EasyRSA"'
   replace: 'export KEY_NAME="server"'

- name: generate the Diffie-Helman parameters using a built-in OpenSSL tool called dhparam
  shell: openssl dhparam -out /etc/openvpn/dh2048.pem 2048

- name: move the server certificates and keys
  copy: src= 'files/{{ item }}' dest=/etc/openvpn
  with_items:
   - server.key
   - server.crt
   - ca.crt
- name: start openvpn server
  service:
   name: openvpn
   state: started
- name: copy the key to the easy-RSA keys
  copy:
   src: files/client.ovpn
   dest: /etc/openvpn/easy-rsa/keys
...
